name: Run Selenium Tests (RemoteWebDriver with Chrome & Firefox)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-chrome:
    name: Test on Chrome
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Tests (Chrome)
        run: mvn clean test -Dbrowser=chrome

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report (Chrome)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-chrome
          path: target/allure-report-chrome